import { ElevenLabsEngine } from './engines/elevenlabs'
import { LocalSynthEngine } from './engines/local'
import { MockMusicEngine } from './engines/mock'
import type { MusicEngine } from './types'

export * from './types'

/**
 * Engine selection.
 *
 * 'elevenlabs' is the real one: full tracks with sung vocals, generated by
 * ElevenLabs Music through our own proxy (`npm run server`), which holds the
 * API key so the browser never sees it.
 *
 * 'local' renders audible audio in the browser from the Style DNA — no key, no
 * network, but a procedural instrumental, not a model. 'mock' returns no audio.
 *
 * Another provider plugs in the same way: implement MusicEngine, add it here,
 * and select it with VITE_ENGINE.
 */
const ENGINES: Record<string, () => MusicEngine> = {
  elevenlabs: () => new ElevenLabsEngine(),
  local: () => new LocalSynthEngine(),
  mock: () => new MockMusicEngine(),
}

const selected = (import.meta.env.VITE_ENGINE as string | undefined) ?? 'local'

export const musicEngine: MusicEngine = (ENGINES[selected] ?? ENGINES.local)()
