import { ElevenLabsEngine } from './engines/elevenlabs'
import { LocalSynthEngine } from './engines/local'
import { MockMusicEngine } from './engines/mock'
import type { MusicEngine } from './types'

export * from './types'

/**
 * Engine selection.
 *
 * 'elevenlabs' is the real one: full tracks with sung vocals, generated by
 * ElevenLabs Music through our own endpoint, which holds the API key so the
 * browser never sees it.
 *
 * 'local' renders audible audio in the browser from the Style DNA — no key, no
 * network, but a procedural instrumental, not a model. 'mock' returns no audio.
 *
 * Another provider plugs in the same way: implement MusicEngine, add it here,
 * and either select it with VITE_ENGINE or teach the probe below about it.
 */
const ENGINES: Record<string, () => MusicEngine> = {
  elevenlabs: () => new ElevenLabsEngine(),
  local: () => new LocalSynthEngine(),
  mock: () => new MockMusicEngine(),
}

export interface EngineInfo {
  name: string
  /** Whether this engine sings the lyrics. */
  vocals: boolean
  /** Whether it produces audio at all. */
  audio: boolean
  /** Whether the server wants an access code before it generates. */
  accessRequired: boolean
}

let accessRequired = false

function describe(engine: MusicEngine): EngineInfo {
  return {
    name: engine.name,
    vocals: engine.name === 'elevenlabs',
    audio: engine.name !== 'mock',
    accessRequired: engine.name === 'elevenlabs' && accessRequired,
  }
}

let resolved: Promise<MusicEngine> | null = null

/**
 * Picks the engine at runtime rather than at build time: it asks our own
 * endpoint whether a provider key is configured. That way a deployment needs
 * one environment variable and nothing else — no build flag to remember, and
 * the same bundle works with or without a backend.
 *
 * VITE_ENGINE still forces a specific engine when set.
 */
export function getEngine(): Promise<MusicEngine> {
  if (resolved) return resolved

  resolved = (async () => {
    const forced = import.meta.env.VITE_ENGINE?.trim()
    if (forced && ENGINES[forced]) return ENGINES[forced]()

    try {
      const response = await fetch('/api/health', { headers: { accept: 'application/json' } })
      if (response.ok) {
        const health = (await response.json()) as { keyConfigured?: boolean; accessRequired?: boolean }
        accessRequired = Boolean(health.accessRequired)
        if (health.keyConfigured) return ENGINES.elevenlabs()
      }
    } catch {
      // No backend reachable — fall through to the local renderer.
    }

    return ENGINES.local()
  })()

  return resolved
}

export async function getEngineInfo(): Promise<EngineInfo> {
  return describe(await getEngine())
}
